name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-python@v2.3.0
      - uses: pre-commit/action@v2.0.3

  test:
    name: ${{ matrix.python-version }}-build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Install Conda environment from environment.yml
        uses: mamba-org/setup-micromamba@v1
        with:
          # environment-file is not assumed anymore
          environment-file: ci/environment.yaml
          create-args: >-
            python=${{ matrix.python-version }}
      - name: Install package
        run: |
          python -m pip install -e .
      - name: Conda list information
        run: |
          conda env list
          conda list
      - name: Run tests
        run: |
          python -m pytest --verbose
